language: node_js
node_js:
  - 14
addons:
  packages:
  - libgconf-2-4
cache:
  npm: true
  directories:
    - ~/.cache
script:
  - eslint 'src/**'
  - yarn test:coveralls
  - yarn test:cypress:ci
deploy: 
  provider: heroku
  api_key: $HEROKU_API
  app: clean-react-vineboneto
  skip-cleanup: true
notifications:
  email: false